server:
  port: 0
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: EDUCATION-SERVICE
          uri: lb://EDUCATION-SERVICE
          predicates:
            - Path=/education/**
          filters:
            - AuthenticationFilter
        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
jwt:
  secret-key: aZQzGvN+f8ApYs2cJpcTHDMkpzJLDkWtcXJwVgxKlQo=
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka