server:
  port: 0
spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: aZQzGvN+f8ApYs2cJpcTHDMkpzJLDkWtcXJwVgxKlQo=
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka